Change istio 0.7 to 0.8
kiali/kiali.github.io pull request #19
Opened 2018-06-14 09:33 UTC by aljesusg

Require [kiali #282](https://github.com/kiali/kiali/pull/282)

2018-06-14 11:08 UTC, jmazzitelli requested changes

2018-06-14 11:08 UTC, jmazzitelli commented on index.md
> +sh cluster-openshift.sh --istio-version 0.8 --kiali-enabled true up
I don't think this is right. I believe you need to specify an exact, specific version - 0.8.0 for example.

2018-06-14 11:09 UTC, jmazzitelli requested changes

2018-06-14 11:09 UTC, jmazzitelli commented on index.md
> +Notice the above command line forces the version of Istio to 0.8 Kiali will support Istio 0.8.0 in the very near future, but for now, we recommend using --istio-version 0.8 if you just want to see wh
This comment now doesn't make sense. I think we should either remove this note (lines 114-5) completely or change it to say something like "we are recommending 0.8.0 in the above command, but keep in mind Kiali is currently in active development to get it to support 0.8.0 fully."

2018-06-20 14:31 UTC, jmazzitelli requested changes

2018-06-20 14:31 UTC, jmazzitelli commented on index.md
> +sh cluster-openshift.sh --istio-version 0.8.0 --kiali-enabled true up
--istio-version doesn't need to be specified now - 0.8.0 is the latest and is the default.

2018-06-20 14:31 UTC, jmazzitelli commented on index.md
> +We are recommending 0.8.0 in the above command, but keep in mind Kiali is currently in active development to get it to support 0.8.0 fully. You could try 0.7.1 instead..
delete this line entirely

2018-06-20 16:39 UTC, aljesusg commented
@jmazzitelli I did the changes

2018-06-21 06:17 UTC, pilhuhn commented
Looks good now

2018-06-21 06:17 UTC, merged